# Generated by Django 5.1.6 on 2025-02-17 04:17

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_employee_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('table_number', models.PositiveIntegerField(verbose_name='Table Number')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacity')),
                ('status', models.SmallIntegerField(choices=[(0, 'Available'), (1, 'Busy')], default=0)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurants.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
