# Generated by Django 5.1.6 on 2025-02-17 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('restaurants', '0003_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='restaurants.restaurant', verbose_name='Restaurant'),
            preserve_default=False,
        ),
    ]
