# Generated by Django 5.1.6 on 2025-02-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_restaurant'),
        ('restaurants', '0003_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('restaurant', 'email'), name='unique_customer_email_per_restaurant'),
        ),
    ]
