# Generated by Django 5.1.6 on 2025-02-17 05:48

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_customer_restaurant'),
        ('restaurants', '0003_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('customer_name', models.CharField(blank=True, max_length=255, verbose_name='Customer Name (if anonymous)')),
                ('status', models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Processing'), (2, 'Completed'), (3, 'Cancelled')], default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tips', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.SmallIntegerField(blank=True, choices=[(0, 'Cash'), (1, 'Credit Card'), (2, 'Debit Card'), (3, 'Mobile Payment'), (4, 'Bank Transfer'), (5, 'Voucher')], null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customers.customer', verbose_name='Customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurants.employee', verbose_name='Employee')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurants.restaurant', verbose_name='Restaurant')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurants.table', verbose_name='Table')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
