# Generated by Django 5.1.6 on 2025-02-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_systems', '0001_initial'),
        ('restaurants', '0003_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='table',
        ),
        migrations.AddField(
            model_name='order',
            name='tables',
            field=models.ManyToManyField(related_name='orders', to='restaurants.table', verbose_name='Tables'),
        ),
    ]
