# Generated by Django 5.1.6 on 2025-02-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_systems', '0003_category_product_orderproduct'),
        ('restaurants', '0003_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='restaurants',
            field=models.ManyToManyField(related_name='products', to='restaurants.restaurant', verbose_name='Restaurants'),
        ),
    ]
