# Generated by Django 5.1.6 on 2025-02-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_systems', '0004_product_restaurants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Product Image'),
        ),
    ]
